[project]
name = "quant-engine"
version = "0.1.0"
description = "Service B - The Quant Engine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "common",
    "pandas",
    "numpy",
    "scikit-learn",
    "redis",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
    "pydantic-settings"
]

[project.scripts]
quant-engine = "quant_engine.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/quant_engine"]
