[project]
name = "lab"
version = "0.1.0"
description = "ML Trainer Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "common",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "psycopg2-binary>=2.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
common = { workspace = true }
