[project]
name = "sentinel"
version = "0.1.0"
description = "Data ingestion service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websockets>=12.0",
    "redis>=5.0.1",
    "asyncpg>=0.29.0",
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "pydantic-settings>=2.1.0",
    "common",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sentinel"]
